#!/usr/bin/env fish

# Check if argument is set (exists)
if not set -q $argv[1]
    # Check if it's a java file
    if [ $argv[1] = "*.java" ]
        # Run pmd, redirect output to out.html, run it with firefox, and remove it
    	$HOME/pmd-bin-6.55.0/bin/run.sh pmd -f html -R rulesets/java/quickstart.xml -d $argv[1] > out.html && firefox ./out.html && sleep 0.1 && rm ./out.html
    else
        # If not a java file, state so
    	echo "Not a java file."
    end
else
    # If no file provided, state so
    echo "No file provided."
end
