#!/usr/bin/env fish


# Get the most recently modified item
set latest (ls -t | head -1)
# Get it's extension (if it exists)
set extension (echo $latest | cut -d '.' -f2)

# Test if the latest item is a file
if [ -f $latest ]
    # Test if it's a c file
    if [ $extension = "c" ]
        # Compile & run
        set binaryname (echo $latest | cut -d'.' -f1)
        gcc $latest -o $binaryname
        exec ./$binaryname
    else
        echo "Recently modified file isn't a c file."
        echo -n "File: "
        echo $latest
    end
else
    echo "Can't find recently modified file."
    echo -n "Found: "
    echo $latest
end
