#!/usr/bin/env fish

# Check if argument is set (exists)
if not set -q $argv[1]
    # Get file extension
    set extension (echo $argv[1] | cut -d '.' -f2)
    # Check if it's a java file
    if [ $extension = "java" ]
        # Check if file exists
        if [ -e $argv[1] ]
        # Run pmd, redirect output to out.html, run it with firefox, and remove it
    	    $HOME/pmd-bin-6.55.0/bin/run.sh pmd -f html -R rulesets/java/quickstart.xml -d $argv[1] > out.html
            firefox ./out.html
            rm ./out.html
        else
            echo "File does not exist."
        end
    else
        # If not a java file, state so
    	echo "Not a java file."
    end
else
    # If no file provided, state so
    echo "No file provided."
end
